<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NP-SADEKUNLE" name="Vernons_Core_SUITE.ChangePasswordTest" tests="12" failures="0" timestamp="16 Jun 2017 08:00:57 GMT" time="180.326" errors="1">
  <testcase name="ChangePasswordtest" time="14.453" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="16.831" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="15.354" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="18.414" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="14.960" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="15.247" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="14.950" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="15.181" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="14.526" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="14.248" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
  <testcase name="ChangePasswordtest" time="13.209" classname="Vernons_Core_SUITE.ChangePasswordTest">
    <error type="java.lang.AssertionError" message="expected [YOUR PASSWORD HAS BEEN SUCCESSFULLY CHANGED] but found [CHANGE PASSWORD]">
      <![CDATA[java.lang.AssertionError: expected [YOUR PASSWORD HAS BEEN SUCCESSFULLY CHANGED] but found [CHANGE PASSWORD]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Vernons_Core_SUITE.ChangePasswordTest.ChangePasswordtest(ChangePasswordTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- ChangePasswordtest -->
  <testcase name="ChangePasswordtest" time="12.953" classname="Vernons_Core_SUITE.ChangePasswordTest"/>
</testsuite> <!-- Vernons_Core_SUITE.ChangePasswordTest -->
